* Arc Tokyo Night Theme

Arc is a flat theme with transparent elements for GTK 3, GTK 2 and various desktop shells, window managers and applications. It's well suited for GTK based desktop environments such as GNOME, Cinnamon, Xfce, Unity, MATE, Budgie etc.

The theme was originally designed and developed by [[https://github.com/horst3180/arc-theme][horst3180]], but the project has been unmaintained since May 2017.

This fork aims to keep the theme updated with new toolkit and desktop environment versions, resolve pre-existing issues, and improve and polish the theme while preserving the original visual design.

This fork of THAT fork is designed to change the color scheme to that of Enkia's Tokyo Night theme for Visual Studio Code.

** Supported toolkits and desktops		

Arc Tokyo Night comes with themes for the following:
- GTK 2
- GTK 3
- GTK 4

** Installation

*** Manual installation

For installing the theme by compiling it from the source code, see [[https://github.com/jnsh/arc-theme/blob/master/INSTALL.md][INSTALL.md]] for build instructions, list of dependencies, build options and additional details.
	
** Issues

If you are experiencing any kind of issues, found a bug, or have a suggestion for improving the theme, please open an issue at [[https://github.com/jnsh/arc-theme/issues][https://github.com/jnsh/arc-theme/issues]].

Some known issues are addressed in [[https://github.com/jnsh/arc-theme/wiki/Common-problems][common problems]].

** License

Arc is available under the terms of the GPL-3.0. See [COPYING](https://github.com/jnsh/arc-theme/blob/master/COPYING) for details.
